In [29]:
print("NAME:- RAMESH BHUTKA")
print("SAP ID:- 5300419003")

NAME:- RAMESH BHUTKA
SAP ID:- 5300419003


In [30]:
import datetime
print(datetime.datetime.now())

2021-05-19 06:06:55.269157


# practical-12

Performing matrix multiplication and finding eigen vectors and eigen values using TensorFlow.

In [2]:
!pip install jovian --upgrade --quiet

In [3]:
import jovian

In [32]:
# Execute this to save new versions of the notebook
jovian.commit(project="practical-12")

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rameshbhutka11/practical-12


'https://jovian.ai/rameshbhutka11/practical-12'

In [9]:
import numpy as np
import tensorflow as tf

# Matrix multiplication

In [21]:
A = [[1, 4, 5], 
    [-5, 8, 9],
    [-1, 4, 8]]

B = [[11, 41, 15], 
    [-5, 8, 91],
    [-1, 41, 8]]

print("Matrix A : \n",A)
print("Matrix B : \n",B)

C = tf.matmul(A, B)
print("Matrix multiplication of Matrix A and B is :\n")
C

Matrix A : 
 [[1, 4, 5], [-5, 8, 9], [-1, 4, 8]]
Matrix B : 
 [[11, 41, 15], [-5, 8, 91], [-1, 41, 8]]
Matrix multiplication of Matrix A and B is :



<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ -14,  278,  419],
       [-104,  228,  725],
       [ -39,  319,  413]], dtype=int32)>

In [24]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

print("Matrix X : \n",X)
print("Matrix Y : \n",Y)

print("Matrix multiplication of Matrix X and Y is :\n")
Z = tf.matmul(X, Y)
Z

Matrix X : 
 [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
Matrix Y : 
 [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]
Matrix multiplication of Matrix X and Y is :



<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]], dtype=int32)>

In [27]:
A = [[1, 4], 
    [-5, 8]]

B = [[11, 41, 15], 
    [-5, 8, 91],
    [-1, 41, 8]]

print("Matrix A : \n",A)
print("Matrix B : \n",B)

C = tf.matmul(A, B)
print("Matrix multiplication of Matrix A and B is :\n")
C

Matrix A : 
 [[1, 4], [-5, 8]]
Matrix B : 
 [[11, 41, 15], [-5, 8, 91], [-1, 41, 8]]


InvalidArgumentError: ignored

# finding eigen vectors and eigen values using TensorFlow

In [33]:
A = tf.constant([[3,1,1],
                 [1,2,1],
                 [1,1,2.]])
values, vectors = tf.linalg.eigh(A)
print("Eigenvalues:")
print(values.numpy())
print()
print("Eigenvectors:")
print(vectors.numpy())

Eigenvalues:
[1.        1.5857866 4.4142137]

Eigenvectors:
[[ 0.         -0.7071068   0.70710665]
 [-0.70710677  0.49999994  0.50000006]
 [ 0.7071068   0.4999999   0.5       ]]


In [34]:
A = tf.constant([[1,-5,3],
                 [2,4,-7],
                 [3,9,-2.]])
values, vectors = tf.linalg.eig(A)
print("Eigenvalues:")
print(values.numpy())
print()
print("Eigenvectors:")
print(vectors.numpy())

Eigenvalues:
[2.7560825 +1.7907736e-07j 0.12195906-7.5705252e+00j
 0.1219592 +7.5705280e+00j]

Eigenvectors:
[[ 0.0614262 +0.9501921j   0.16093378-0.34744072j  0.13818479+0.35709897j]
 [-0.01236172-0.19122145j  0.35604456+0.53046155j  0.38952377-0.50638765j]
 [ 0.01535366+0.23750286j -0.33046412+0.57967365j -0.2923802 -0.5997849j ]]


In [49]:
A = tf.constant([[5, 1], [3, 3.]])
print(A)

values, vectors = tf.linalg.eig(A)
print("Eigenvalues:")
print(values)
print()
print("Eigenvectors:")
print(vectors)


tf.Tensor(
[[5. 1.]
 [3. 3.]], shape=(2, 2), dtype=float32)
Eigenvalues:
tf.Tensor([1.9999999+0.j 5.9999995+0.j], shape=(2,), dtype=complex64)

Eigenvectors:
tf.Tensor(
[[-0.31622776+0.j  0.7071068 +0.j]
 [ 0.9486833 +0.j  0.7071068 +0.j]], shape=(2, 2), dtype=complex64)


In [51]:
A = np.array([[5, 1], [3, 3]])
print(A)


values, vectors = np.linalg.eig(A)
print("Eigenvalues:")
print(values)
print()
print("Eigenvectors:")
print(vectors)


[[5 1]
 [3 3]]
Eigenvalues:
[6. 2.]

Eigenvectors:
[[ 0.70710678 -0.31622777]
 [ 0.70710678  0.9486833 ]]


In [53]:
jovian.commit(project="practical-12")


[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rameshbhutka11/practical-12


'https://jovian.ai/rameshbhutka11/practical-12'