## Practical 2: Sovling a system of linear equations

In [31]:
print("Name :- Ramesh Bhutka")
print("Sap ID:- 53004190003")

Name :- Ramesh Bhutka
Sap ID:- 53004190003


In [32]:
from datetime import datetime
time = datetime.now()
print(time)

2021-03-07 12:24:31.091571


# Equations

### 4x + 3y = −2
### 8x − 2y = 12

In [33]:
print(time,"\n")
import numpy as np

2021-03-07 12:24:31.091571 



In [34]:
print(time,"\n")
A = np.array([[4,3],[8,-2]])
print("Matrix A is : \n", A)

2021-03-07 12:24:31.091571 

Matrix A is : 
 [[ 4  3]
 [ 8 -2]]


In [35]:
print(time,"\n")
A_inv = np.linalg.inv(A)
print("A inverse : \n", A_inv)

2021-03-07 12:24:31.091571 

A inverse : 
 [[ 0.0625   0.09375]
 [ 0.25    -0.125  ]]


In [36]:
print(time,"\n")
b = np.array([[-2],[12]])
print("Scalar b is : \n", b)

2021-03-07 12:24:31.091571 

Scalar b is : 
 [[-2]
 [12]]


In [37]:
print(time,"\n")
x = A_inv.dot(b)
print("Answer  : \n", x)

2021-03-07 12:24:31.091571 

Answer  : 
 [[ 1.]
 [-2.]]


## WITH RANDOM NUMBER

In [53]:
print(time,"\n")
A = np.random.randint(10, size=(3,3))
print("Matrix A is : \n", A)

2021-03-07 12:24:31.091571 

Matrix A is : 
 [[6 0 5]
 [9 0 7]
 [6 5 9]]


In [54]:
print(time,"\n")
A_inv = np.linalg.inv(A)
print("A inverse : \n", A_inv)

2021-03-07 12:24:31.091571 

A inverse : 
 [[-2.33333333  1.66666667  0.        ]
 [-2.6         1.6         0.2       ]
 [ 3.         -2.          0.        ]]


In [55]:
print(time,"\n")
b = np.random.randint(10, size=(3,1))
print("Scalar b is : \n", b)

2021-03-07 12:24:31.091571 

Scalar b is : 
 [[6]
 [3]
 [2]]


In [56]:
print(time,"\n")
x = A_inv.dot(b)
print("Answer  : \n", x)

2021-03-07 12:24:31.091571 

Answer  : 
 [[ -9. ]
 [-10.4]
 [ 12. ]]
